ALTER TABLE partidos
  ADD COLUMN IF NOT EXISTS faltas_local_1er INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS faltas_local_2do INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS faltas_visitante_1er INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS faltas_visitante_2do INTEGER DEFAULT 0;
